#### 1. Find Factorial

* Using numpy library and its functions find the factorial of all numbers from 1 till 'n'
* 'n' is the input from the user
* For eg.: Input = 5
* Output should be [1!, 2!, 3!, 4!, 5!] i.e. [1,2,6,24,120]

In [1]:
import numpy as np

In [5]:
def factorial(n, *, method = 1):
    """This function achieves same results using two different numpy functions."""
    
    if method == 1:
        # using aggregate function
        return np.multiply.accumulate(np.arange(1,n+1))
    
    elif method == 2:
        # using cumprod function
        return np.cumprod(np.arange(1,n+1))

In [6]:
n = int(input("Enter a Number: "))

print("The factorial of all integers from 1 to ", n, " is ", factorial(n)) # using aggregate function
print("The factorial of all integers from 1 to ", n, " is ", factorial(n, method = 2)) # using cumprod function

Enter a Number: 5
The factorial of all integers from 1 to  5  is  [  1   2   6  24 120]
The factorial of all integers from 1 to  5  is  [  1   2   6  24 120]


#### 2. Summarizing our data

* Write a function that returns a summary of our data.
* The function should return
    * Minimum value
    * Maximum Value
    * Mean
    * 1st Quartile i.e. 25th percentile
    * 2nd Quartile i.e. Median
    * 3rd Quartile i.e. 75th percentile
    * Variance
    * Standard Deviation
* Take the data as an input from the csv file using pandas library
* **Note:** .csv file is attached with this notebook.

In [6]:
import numpy as np
import pandas as pd

In [7]:
def summary(data):
    print("Min         : ", np.min(data))
    print("Max         : ", np.max(data))
    print("Mean        : ", np.mean(data))
    print("1st Quartile: ", np.percentile(data, 25))
    print("Median      : ", np.median(data))
    print("3rd Quartile: ", np.percentile(data, 75))
    print("Var         : ", np.var(data))
    print("Std         : ", np.std(data))

In [11]:
data = pd.read_csv("./data.csv")['Values'].values
data

array([428.  , 989.  , 662.  , 723.  , 957.  , 256.  , 931.  , 376.  ,
       837.  , 539.  , 763.  , 458.  , 749.  , 340.  , 522.  , 806.  ,
       412.  , 687.  , 941.  , 973.  , 757.  , 927.  , 459.  ,   3.32,
       445.  ,  92.2 , 248.  , 597.  , 153.  , 739.  ])

In [12]:
summary(data)

Min         :  3.32
Max         :  989.0
Mean        :  592.3173333333333
1st Quartile:  416.0
Median      :  629.5
3rd Quartile:  795.25
Var         :  75977.03871288888
Std         :  275.6393272247066


#### 3. Student Report

* Consider the given matrix
    * [45,60,55,70,70,38]<br>[39,48,88,42,37,38]<br>[32,77,60,39,71,38]
    * Here each row stands for marks obtained by a student and each column represents each subject i.e. 3 students and 6 subjects
* Solve following questions for the given marks matrix
    * Per subject how many students failed?
    * How many subjects did each student fail in?
    * What is the highest score in each subject?
    * What is the lowest score in each subject?

In [2]:
import numpy as np

In [7]:
student_data = np.array([[45,60,55,70,70,38],[39,48,88,42,37,38],[32,77,60,39,71,38]])
student_data

array([[45, 60, 55, 70, 70, 38],
       [39, 48, 88, 42, 37, 38],
       [32, 77, 60, 39, 71, 38]])

In [11]:
np.sum(student_data<40,axis =0)

array([2, 0, 0, 1, 1, 3])

In [6]:
np.sum(student_data<40, axis = 1)

array([1, 3, 3])

In [8]:
np.max(student_data, axis = 0)

array([45, 77, 88, 70, 71, 38])

In [9]:
np.min(student_data, axis = 0)

array([32, 48, 55, 39, 37, 38])

In [1]:
import numpy as np

In [2]:
help(np.multiply.accumulate)

Help on built-in function accumulate:

accumulate(...) method of numpy.ufunc instance
    accumulate(array, axis=0, dtype=None, out=None)
    
    Accumulate the result of applying the operator to all elements.
    
    For a one-dimensional array, accumulate produces results equivalent to::
    
      r = np.empty(len(A))
      t = op.identity        # op = the ufunc being applied to A's  elements
      for i in range(len(A)):
          t = op(t, A[i])
          r[i] = t
      return r
    
    For example, add.accumulate() is equivalent to np.cumsum().
    
    For a multi-dimensional array, accumulate is applied along only one
    axis (axis zero by default; see Examples below) so repeated use is
    necessary if one wants to accumulate over multiple axes.
    
    Parameters
    ----------
    array : array_like
        The array to act on.
    axis : int, optional
        The axis along which to apply the accumulation; default is zero.
    dtype : data-type code, optional
        

In [3]:
np.multiply.accumulate(5)

AxisError: axis 5 is out of bounds for array of dimension 0